// f1db.ts — client-side access to pre-extracted f1db JSON files.
// Primary source for historical F1 data (seasons prior to current year).
// Generated by: npm run data:extract

import type { JolpicaCareerSeason } from './jolpica'

const BASE = '/seasons/f1db'
const CURRENT_YEAR = 2026

// ── Cached fetch helpers ──────────────────────────────────────────────────────

const cache = new Map<string, Promise<unknown>>()

function fetchOnce<T>(path: string): Promise<T> {
  if (!cache.has(path)) {
    cache.set(path, fetch(path).then(r => {
      if (!r.ok) throw Object.assign(new Error(`f1db fetch failed: ${path}`), { status: r.status })
      return r.json()
    }))
  }
  return cache.get(path) as Promise<T>
}

// ── ID normalization ──────────────────────────────────────────────────────────
// Resolves Jolpica driver IDs (max_verstappen, hamilton) to f1db slugs (max-verstappen, lewis-hamilton).

type DriverIdMap = Record<string, string>

function loadDriverIdMap(): Promise<DriverIdMap> {
  return fetchOnce<DriverIdMap>(`${BASE}/driver-id-map.json`)
}

async function resolveDriverId(jolpicaId: string): Promise<string> {
  // Direct f1db slug passthrough (already uses hyphens)
  const hyphenated = jolpicaId.replace(/_/g, '-')

  const map = await loadDriverIdMap().catch(() => ({} as DriverIdMap))

  // Try new-style (max_verstappen → max-verstappen)
  if (map[jolpicaId]) return map[jolpicaId]
  // Try old-style (hamilton → lewis-hamilton)
  const lastPart = jolpicaId.split('_').pop() ?? jolpicaId
  if (map[lastPart]) return map[lastPart]
  // Fallback: underscore → hyphen (works for most modern drivers)
  return hyphenated
}

// ── Career data ───────────────────────────────────────────────────────────────

type CareerAllJson = Record<string, JolpicaCareerSeason[]>

function loadCareerAll(): Promise<CareerAllJson> {
  return fetchOnce<CareerAllJson>(`${BASE}/career-all.json`)
}

export async function fetchF1dbDriverCareer(jolpicaDriverId: string): Promise<JolpicaCareerSeason[]> {
  const [f1dbId, careerAll] = await Promise.all([
    resolveDriverId(jolpicaDriverId),
    loadCareerAll(),
  ])
  return careerAll[f1dbId] ?? []
}

// ── Season standings ──────────────────────────────────────────────────────────

export interface F1dbDriverStanding {
  driverId: string
  position: number
  positionText: string
  points: number
  wins: number
  championshipWon: boolean
}

export async function fetchF1dbStandings(year: number): Promise<F1dbDriverStanding[]> {
  if (year >= CURRENT_YEAR) return []
  return fetchOnce<F1dbDriverStanding[]>(`${BASE}/standings/${year}.json`).catch(() => [])
}

// ── Race results ──────────────────────────────────────────────────────────────

export interface F1dbRaceResult {
  driverId: string
  position: number
  points: number
}

export interface F1dbRace {
  id: number
  round: number
  grandPrixId: string
  date: string
  results: F1dbRaceResult[]
}

export async function fetchF1dbRaces(year: number): Promise<F1dbRace[]> {
  if (year >= CURRENT_YEAR) return []
  return fetchOnce<F1dbRace[]>(`${BASE}/races/${year}.json`).catch(() => [])
}
